-- =============================================================================
-- seed_banks.sql — Kopra by Mandiri beneficiary bank codes
--
-- The bank code a Kopra bulk-transfer file carries for every transfer that leaves
-- Mandiri: an 8-character BIC, one per bank. Source: the sheet "List of Bank Codes"
-- in "(KOPRA) New Format Transfer Consolidated.xlsx", the list Mandiri ships with
-- its Multiple Transfer by File Upload templates (as of 4 October 2024).
--
-- Seeded rather than typed by hand because a wrong code is caught by nothing we
-- own: Kopra rejects the whole file, and the transfers meant to go out that
-- morning do not.
--
-- Bank Mandiri itself is absent from Mandiri's own list — a transfer to Mandiri is
-- In-House and carries no beneficiary bank code at all. It is added here as the
-- single row flagged `is_self`, so an account at Mandiri can still be picked on a
-- form and the exporter can tell In-House apart from everything else.
--
-- Idempotent: re-running refreshes the names and leaves the ids alone, so the
-- foreign keys pointing here survive a re-seed.
-- =============================================================================
INSERT INTO `banks` (`bank_code`, `bank_name`, `is_self`) VALUES
  ('BMRIIDJA', 'Bank Mandiri', 1),
  ('ALTOIDJ1', 'Alto', 0),
  ('ANZBIDJX', 'ANZ Indonesia', 0),
  ('ATJSIDJ2', 'Artajasa', 0),
  ('BKKBIDJA', 'BANGKOK BANK PUBLIC, CO. LTD.', 0),
  ('MAYOIDJA', 'BANK HIBANK INDONESIA', 0),
  ('PDRIIDJA', 'BANK RIAU KEPRI SYARIAH', 0),
  ('CENAIDJA', 'BCA (Bank Central Asia)', 0),
  ('SYCAIDJ1', 'BCA Syariah', 0),
  ('SYJBIDJ1', 'BJB Syariah', 0),
  ('BNINIDJA', 'BNI (Bank Negara Indonesia)', 0),
  ('BNPAIDJA', 'BNP Paribas Indonesia', 0),
  ('BRINIDJA', 'BRI (Bank Rakyat Indonesia)', 0),
  ('BTANIDJA', 'BTN (Bank Tabungan Negara)', 0),
  ('SYBTIDJ1', 'BTN (Bank Tabungan Negara) Syariah', 0),
  ('SUNIIDJA', 'BTPN', 0),
  ('PUBAIDJ1', 'BTPN Syariah', 0),
  ('SYACIDJ1', 'Bank Aceh Syariah', 0),
  ('LOMAIDJ1', 'Bank Amar Indonesia', 0),
  ('ARTGIDJA', 'Bank Artha Graha Internasional', 0),
  ('ABALIDBS', 'Bank BPD Bali', 0),
  ('PDYKIDJ1', 'Bank BPD DIY', 0),
  ('SYYKIDJ1', 'Bank BPD DIY Unit Usaha Syariah', 0),
  ('PDBBIDJ1', 'Bank Banten', 0),
  ('PDBKIDJ1', 'Bank Bengkulu', 0),
  ('BBAIIDJA', 'Bank Bumi Arta', 0),
  ('BCIAIDJA', 'Bank Capital Indonesia', 0),
  ('BDKIIDJ1', 'Bank DKI Jakarta', 0),
  ('SYDKIDJ1', 'Bank DKI Unit Usaha Syariah', 0),
  ('BDINIDJA', 'Bank Danamon', 0),
  ('SYBDIDJ1', 'Bank Danamon Unit Syariah', 0),
  ('FAMAIDJ1', 'Bank Fama International', 0),
  ('GNESIDJA', 'Bank Ganesha', 0),
  ('IBKOIDJA', 'Bank IBK Indonesia', 0),
  ('IAPTIDJA', 'Bank Ina Perdana', 0),
  ('BIDXIDJA', 'Bank Index Selindo', 0),
  ('PDJMIDJ1', 'Bank Jambi', 0),
  ('SYJMIDJ1', 'Bank Jambi Unit Usaha Syariah', 0),
  ('JSABIDJ1', 'Bank Jasa Jakarta', 0),
  ('PDJGIDJ1', 'Bank Jateng', 0),
  ('SYJGIDJ1', 'Bank Jateng Syariah', 0),
  ('PDJTIDJ1', 'Bank Jatim', 0),
  ('SYJTIDJ1', 'Bank Jatim Unit Usaha Syariah', 0),
  ('PDKBIDJ1', 'Bank Kalbar', 0),
  ('SYKBIDJ1', 'Bank Kalbar Syariah', 0),
  ('PDKSIDJ1', 'Bank Kalsel', 0),
  ('SYKSIDJ1', 'Bank Kalsel Syariah', 0),
  ('PDKGIDJ1', 'Bank Kalteng', 0),
  ('PDKTIDJ1', 'Bank Kaltim', 0),
  ('SYKTIDJ1', 'Bank Kaltim Unit Syariah', 0),
  ('PDLPIDJ1', 'Bank Lampung', 0),
  ('BUMIIDJA', 'Bank MNC Internasional', 0),
  ('PDMLIDJ1', 'Bank Maluku', 0),
  ('SIHBIDJ1', 'Bank Mandiri Taspen', 0),
  ('MASDIDJ1', 'Bank Maspion Indonesia', 0),
  ('MAYAIDJA', 'Bank Mayapada Internasional', 0),
  ('MEGAIDJA', 'Bank Mega', 0),
  ('BUTGIDJ1', 'Bank Mega Syariah', 0),
  ('MEDHIDS1', 'Bank Mestika Dharma', 0),
  ('MHCCIDJA', 'Bank Mizuho Indonesia', 0),
  ('MUABIDJA', 'Bank Muamalat Indonesia', 0),
  ('BMSEIDJA', 'Bank Multiarta Sentosa', 0),
  ('PDNBIDJ1', 'Bank NTB Syariah', 0),
  ('LMANIDJ1', 'Bank OKE', 0),
  ('PDIJIDJ1', 'Bank Papua', 0),
  ('BBBAIDJA', 'Bank Permata', 0),
  ('SYBBIDJ1', 'Bank Permata Syariah', 0),
  ('BPIAIDJA', 'Bank Resona Perdania', 0),
  ('SAHMIDJA', 'Bank Sahabat Sampoerna', 0),
  ('SBJKIDJA', 'Bank Sinarmas', 0),
  ('PDWSIDJA', 'Bank Sulselbar', 0),
  ('SYWSIDJ1', 'Bank Sulselbar Syariah', 0),
  ('PDWGIDJ1', 'Bank Sulteng', 0),
  ('PDWRIDJ1', 'Bank Sultra', 0),
  ('PDWUIDJ1', 'Bank SulutGo', 0),
  ('PDSBIDJ1', 'Bank Sumbar (Bank Nagari)', 0),
  ('SYSBIDJ1', 'Bank Sumbar (Bank Nagari) Syariah', 0),
  ('BSSPIDSP', 'Bank Sumsel Babel', 0),
  ('SYSSIDJ1', 'Bank Sumsel Babel Syariah', 0),
  ('PDSUIDJ1', 'Bank Sumut', 0),
  ('SYSUIDJ1', 'Bank Sumut Unit Usaha Syariah', 0),
  ('BSMDIDJA', 'Bank Syariah Indonesia', 0),
  ('VICTIDJ1', 'Bank Victoria International', 0),
  ('SWAGIDJ1', 'Bank Victoria Syariah', 0),
  ('BSDRIDJA', 'Bank Woori Saudara Indonesia 1906', 0),
  ('BOFAID2X', 'Bank of America', 0),
  ('BKCHIDJA', 'Bank of China (Hong Kong) Limited', 0),
  ('BKIDIDJA', 'Bank of India Indonesia', 0),
  ('SDOBIDJ1', 'Bukopin Syariah', 0),
  ('MCORIDJA', 'CCB (China Construction Bank) Indonesia', 0),
  ('BNIAIDJA', 'CIMB Niaga', 0),
  ('SYNAIDJ1', 'CIMB Niaga Unit Usaha Syariah', 0),
  ('CITIIDJX', 'CITIBANK, N.A.', 0),
  ('CTCBIDJA', 'CTBC (Chinatrust) Indonesia', 0),
  ('DBSBIDJA', 'DBS Indonesia', 0),
  ('DEUTIDJA', 'Deutsche Bank AG', 0),
  ('FINTIDJ1', 'Finnet Indonesia', 0),
  ('HSBCIDJA', 'HSBC Indonesia', 0),
  ('ICBKIDJA', 'ICBC Indonesia', 0),
  ('LPEIIDJ1', 'Indonesia Eximbank', 0),
  ('CICTIDJA', 'J Trust Bank', 0),
  ('CHASIDJX', 'JPMorgan Chase Bank', 0),
  ('JPNAIDJ1', 'Jalin Pembayaran Elektronik', 0),
  ('HNBNIDJA', 'KEB Hana Bank Indonesia', 0),
  ('KSEIIDJ1', 'KSEI', 0),
  ('BLPSIDJ1', 'LEMBAGA PENJAMIN SIMPANAN', 0),
  ('BOTKIDJX', 'MUFG Bank, Ltd', 0),
  ('IBBKIDJA', 'Maybank Indonesia', 0),
  ('SYBKIDJ1', 'Maybank Indonesia Unit  Syariah', 0),
  ('LFIBIDJ1', 'Nobu (Nationalnobu) Bank', 0),
  ('NISPIDJA', 'OCBC NISP', 0),
  ('SYONIDJ1', 'OCBC NISP Unit Syariah', 0),
  ('HRDAIDJ1', 'PT ALLO BANK INDONESIA', 0),
  ('NETBIDJA', 'PT BANK ALADIN SYARIAH ,TBK', 0),
  ('SYATIDJ1', 'PT BANK JAGO TBK UNIT USAHA SYARIAH', 0),
  ('PDJBIDJA', 'PT BPD JABAR DAN BANTEN', 0),
  ('PDNTIDJA', 'PT BPD NUSA TENGGARA TIMUR', 0),
  ('BBLUIDJA', 'PT Bank Digital BCA', 0),
  ('BBUKIDJA', 'PT Bank KB Bukopin', 0),
  ('NANOIDJ1', 'PT Bank Nano Syariah', 0),
  ('SSPIIDJA', 'PT Bank Seabank Indonesia', 0),
  ('BUSTIDJ1', 'PT Krom Bank Indonesia Tbk', 0),
  ('PTENIDJ1', 'PT PENYELESAIAN TRANSAKSI ELEKTRONIK NASIONAL', 0),
  ('YUDBIDJ1', 'PT. BANK NEO COMMERCE TBK.', 0),
  ('AGTBIDJA', 'PT. BANK RAYA INDONESIA Tbk', 0),
  ('MEEKIDJ1', 'PT. BANK SHINHAN INDONESIA', 0),
  ('JAGBIDJA', 'PT. Bank Jago, Tbk', 0),
  ('KPEIIDJ2', 'PT. KPEI-CCP-PUVA', 0),
  ('PINBIDJA', 'Panin Bank', 0),
  ('ARFAIDJ1', 'Panin Dubai Syariah Bank', 0),
  ('AWANIDJA', 'QNB Indonesia', 0),
  ('IDMOIDJ1', 'SBI Indonesia', 0),
  ('SCBLIDJX', 'Standard Chartered Bank', 0),
  ('BBIJIDJA', 'UOB Indonesia', 0)
ON DUPLICATE KEY UPDATE `bank_name` = VALUES(`bank_name`), `is_self` = VALUES(`is_self`);
